name: api
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  connectivity_plus: ^2.3.7
  device_info_plus: ^4.1.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  intl: ^0.17.0
  logger: ^1.1.0
  package_info_plus: ^1.4.3+1
  string_scanner: ^1.1.0
  uuid: ^3.0.6
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: