on: 
  push:
    tags:
      - '*'
name: test, build apk
jobs:
  build:
    # job name
    name: Build APK
      # build env ubuntu
    runs-on: ubuntu-latest
    steps:
      # branch build code
      - uses: actions/checkout@v3
      # setup env
      - uses: actions/setup-java@v3
        # using java ver
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      # setup flutter env default v2 -> https://github.com/subosito/flutter-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.3'
          channel: 'stable'
      - name: run flutter version
        run: flutter --version
      # run pub get
      - name: run pub get
        run: flutter pub get
      # run analyze
      - run: dart analyze
      # run test
      - run: flutter test
      # run build
      - run: flutter build apk --flavor dev -t lib/main_dev.dart --release --split-per-abi
      - run: ls ./build/app/outputs/flutter-apk
      # release apk
      - name: Create a Release APK
        # setup flutter env default v1 -> https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          # setup token:
          # - open https://github.com/settings/tokens
          # - Tạo một token mới với scope là quyền truy cập repo và copy token đó
          # - Tới trang cài đặt của repository, tại tab Secrets thêm một secret mới
          #   với cùng tên mà bạn đã sử dụng ở phần code bên trên (ở đây là TOKEN) 
          #   và dán token bạn vừa copy vào box value.
          token: ${{ secrets.TOKEN }}